### ISSUE TITLE
Provable Authn Error at brave broswer

### ISSUE THREAD

**Issue by script-money** [onflow/fcl-dev-wallet#83]
I use brave 1.34.80, when selecting an account, show this error and can't read the state from the emulator.
But chrome 97 has no problem.
Error below
```
 Error: INVARIANT Encode Message From Provable Authn Error: timestamp must be defined
    at Object.exports.invariant (/app/node_modules/@onflow/util-invariant/dist/util-invariant.js:1:48)
    at Object.encodeMessageForProvableAuthnSigning (/app/node_modules/@onflow/fcl/dist/fcl.js:1:35985)
    at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/prove-authn.js:71:170)
    at Object.apiResolver (/app/node_modules/next/dist/server/api-utils.js:102:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.handleApiRequest (/app/node_modules/next/dist/server/next-server.js:1064:9)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:951:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:222:32)
    at async Server.run (/app/node_modules/next/dist/server/next-server.js:1135:29)
    at async Server.handleRequest (/app/node_modules/next/dist/server/next-server.js:325:20) 
```

**Comment by gregsantos** [comment]
I wasn't able to replicate using Brave 1.34.80.
What version of FCL are you using in your app?

**Comment by script-money** [comment]
> I wasn't able to replicate using Brave 1.34.80. What version of FCL are you using in your app?

@onflow/fcl@^0.0.77

**Comment by elpunkt** [comment]
Had the same issue in firefox 96 and chromium 97.0.4692.99. Fore some reason, fcl did not add a timestamp to the body of the POST request to `/api/prove-authn`. 

Upgarding to @onflow/fcl@^0.0.78 solved the issue for me.
